AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure for Cloud Resume - S3 bucket for static website hosting.

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket for resume website
    Default: resume

Resources:
  ResumeBucket:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-s3-bucket.html
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Value: !Ref ResumeBucket
    Description: Name of the S3 bucket
  BucketArn:
    Value: !GetAtt ResumeBucket.Arn
    Description: ARN of the S3 bucket